name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./EmployeeAPI/EmployeeAPI.csproj

    - name: Build
      run: dotnet build ./EmployeeAPI/EmployeeAPI.csproj --no-restore

    - name: Publish
      run: dotnet publish ./EmployeeAPI/EmployeeAPI.csproj -c Release -o publish